### PR TITLE
refactor: use virtual text to display filename and line numbers

### LINKED ISSUE #28: feature request: Exclude filename from editor changes
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

First, thanks for another great plugin!

When a list includes both filename and test matches for a substitution command, both values are modified. Modifying a filename produces an error "does not support adding or reordering quickfix items".

list:
`app/controllers/foo_bar.rb                  ┃   54┃@foo_bar = "baz"`

substituter:
`%s/foo_bar/foo_baz`

### Provide background

I am trying to substitute matching terms, excluding filename matches. I can do this by modifying my search (e.g. "foo_bar$"), but I wonder if ignoring filenames in the *editor* makes sense as a default behavior.

### What is the significance of this feature?

nice to have

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by stevearc**
closes #28

~~This refactors how we render the quickfix to use inline virtual text for the filename + line number. That means the only actual buffer text is the text from the grep/make/whatever results.~~

This refactors how we render the quickfix to use inline virtual text for the line number, and to use the IDs of the extmarks to match the quickfix item instead of trying to parse the line itself. Since we don't have to parse the filename, we can handle cases where the filename gets mangled (say, by a rogue `:%s` replacement).

 This has a number of benefits:

- It's now impossible to accidentally do a find/replace operation that mucks with the filenames and causes the `:w` to fail
- The logic for the editor is now much simpler and more reliable, because it fetches the extmarks instead of parsing a filename + line number from the buffer
- ~~No need for the "constrain cursor" logic anymore~~ (we still need this because we decided to keep the filename in the buffer)
- No need for special syntax file, as all highlighting is handled directly in the virtual text

~~But it comes with one notable drawback: You can no longer use `/` to search for a filename in the list of results~~

### CODE REVIEW

**Comment by datwaft** [comment]
Just as an idea as I don't know how factible it could be, what about a command that changes the filename and line number from virtual text into real text? That way it could be used to search by filename.
Maybe after saving with that text present in the buffer it could return to using virtual text, that way it is only present sometimes.

**Comment by stevearc** [comment]
oof...a large part of the benefit of this change is not having to deal with the filename + lnum actually _in_ the buffer. I'd prefer to not have to support that anymore

**Comment by stevearc** [comment]
Hmmm...something I found that I really don't like: this makes it easier to perform edits on the text in the quickfix, but you can no longer make modifications _based_ on the filename. For example, doing `:g/test/d` used to remove all entries with "test" in the filename, but no longer.
That said, the previous way this worked wasn't great either because it would operate if _either_ the filename _or_ the contents matched. I need to find some intuitive way to bring back filename-based mutations. Maybe the only one that matters is filtering.

**Comment by stevearc** [comment]
Okay, I think I've found a better system. Instead of rendering `<virtual filename> <virtual lineno> text`, I'm going to render `filename <virtual lineno> text`. This allows us to use the same extmark ID tracking to recover the filename, so it doesn't matter if the filename gets mangled. Since the filename is now back in the normal buffer text, searching for filenames and deleting lines based on matching the filename works again.

I'm going to let this bake for a while and if I don't discover any other issues, I'll merge.

**Pull request merged**
